### ISSUE TITLE
Ruby Spec tests - test filtering

### ISSUE THREAD

**Issue by MSP-Greg** [MSP-Greg/ruby_on_windows#2]
@eregon

I created a blank repo for general build, test, and patch  discussions re Ruby on Windows.

There's patch (see #1) that allows windows ruby to use fractional seconds for file times.  There are several spec tests that have `platform_is :linux do` because of this issue.  Obviously, one can allow windows test by using `platform_is :linux, :windows do`, but that isn't restricting the version.

So, I'd like the test to run if the platform is :linux or it's :windows and the version >= 2.5.0.

In what manner would you prefer to constrain a test for that type of criteria?

Thanks.

**Comment by eregon** [comment]
There is unfortunately no easy way to do this currently.

It is however easier if we only need to test this extra feature on platforms supporting it (not asserting that it does not work on the other platforms, which I think is not so useful in this case).
The best way currently is to use shared specs:
```ruby
describe :file_mtime_us, shared: true do
  it "returns the modification Time of the file with microseconds" do
    ...
  end
end

platform_is :linux do
  it_should_behave_like :file_mtime_us
end

platform_is :windows do
  ruby_version_is "2.5" do
    it_should_behave_like :file_mtime_us
  end
end
```

Going forward I would like to improve this as described in https://github.com/ruby/mspec/issues/30.
